### PR TITLE
Add GlobalVars and PlantedC4 offsets, Add distance esp

### PR DESCRIPTION
**Pull request by mildnsj**
distance esp and offsets for future pull.
From Bottame & ToOl_UmbRelLa (fix)

### CODE REVIEW

**Comment by Fr0go1** [comment]
would you be ok if i used this in my version?

**Comment by Fr0go1** [comment]
i will give credit

**Comment by mildnsj** [comment]
> i will give credit

ofc do as you want

**Comment by TKazer** [comment]
1. Move distance draw code to Render.hpp, and you can use the Format() (in Format.hpp) to format distance text.
2. Change "globals.cpp" to "Globals.hpp", Also inline the GetDataAddressWithOffset() function.

**Comment by TKazer** [comment]
Also thanks for sharing.

**Comment by mildnsj** [comment]
> 1. Move distance draw code to Render.hpp, and you can use the Format() (in Format.hpp) to format distance text.
> 2. Change "globals.cpp" to "Globals.hpp", Also inline the GetDataAddressWithOffset() function.

alr

**Comment by mildnsj** [comment]
We'll open a new one soon.

**Pull request closed without merging**
